# -*- coding: utf-8 -*-
"""data_explorer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEvGqc-MGOpTWMYqKJJW9FNvXGl0hHPa
"""

import pandas as pd

def analyze_dataset(file_path):
    print("--- Loading Dataset ---")
    df = pd.read_csv(file_path)

    print("\n--- Basic Information ---")
    print(f"Total Rows: {df.shape[0]}")
    print(f"Total Columns: {df.shape[1]}")

    print("\n--- Column Names & Data Types ---")
    print(df.dtypes)

    print("\n--- Missing Values Summary ---")
    print(df.isnull().sum())

    print("\n--- Statistical Summary ---")
    print(df.describe())

# Example usage (replace 'sample.csv' with any CSV file you have)
if __name__ == "__main__":
    try:
        analyze_dataset('sample.csv')
    except FileNotFoundError:
        print("Please place a sample.csv file in the same folder to run the analysis!")